print("""Hipp hipp hurra!
Hipp hipp hurra!
Hipp hipp hurra!
Hipp hipp hurra!
Hipp hipp hurra!
Hipp hipp hurra!
Hipp hipp hurra!
Hipp hipp hurra!
Hipp hipp hurra!
Hipp hipp hurra!
Hipp hipp hurra!
Hipp hipp hurra!
Hipp hipp hurra!
Hipp hipp hurra!
Hipp hipp hurra!
Hipp hipp hurra!
Hipp hipp hurra!
Hipp hipp hurra!
Hipp hipp hurra!
Hipp hipp hurra!
""")